version: 2.1

aliases:
  - &restore-cache
      restore_cache:
        keys:
          - dependencies-cache-{{ checksum "yarn.lock" }}

  - &save-cache
      save_cache:
        paths:
          - node_modules
        key: dependencies-cache-{{ checksum "yarn.lock" }}

  - &install-deps
      run:
        name: Build
        command: |
          yarn global add lerna
          yarn

jobs:
  build-and-test:
    docker:
      - image: circleci/node:14

    # This makes all commands from here on out relative to service-a
    working_directory: ~/ci

    steps:
      - checkout:
          path: ~/ci
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Compile
          command: |
            yarn lerna run compile
      - run:
          name: Test
          command: |
            yarn lerna run test

  publish:
    docker:
      - image: circleci/node:14

    # This makes all commands from here on out relative to service-a
    working_directory: ~/ci

    steps:
      - checkout:
          path: ~/ci
      - *restore-cache
      - *install-deps
      - *save-cache
      - run:
          name: Publish
          command: |
            yarn lerna publish

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: npm-publish
          requires:
            - build-and-test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

