version: 2.1

aliases:
  - &restore-cache
      restore_cache:
        keys:
          - dependencies-cache-{{ checksum "yarn.lock" }}

  - &save-cache
      save_cache:
        paths:
          - node_modules
        key: dependencies-cache-{{ checksum "yarn.lock" }}

jobs:
  publish:
    docker:
      - image: circleci/node:14
    working_directory: ~/ci

  build-and-test:
    docker:
      - image: circleci/node:14

    # This makes all commands from here on out relative to service-a
    working_directory: ~/ci

    steps:
      - checkout:
          # Since our working_directory is deeper than the root,
          # remind the job where it needs to checkout.
          path: ~/ci
      - *restore-cache
      - run:
          name: Build
          command: |
            yarn global add lerna
            yarn
      - *save-cache
      - run:
          name: Compile
          command: |
            lerna run compile
      - run:
          name: Test
          command: |
            lerna run test
      - run:
          name: Publish
          command: |
            lerna publish
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/

workflows:
  version: 2
  service-a:
    jobs:
      - build-and-test:
          context: npm-credentials

